//
// Created by mauri on 30/10/2023.
//

#ifndef PRUEBAPROYECTOMCAV_SOLOPARAQUEAPAREZCACON_H
#define PRUEBAPROYECTOMCAV_SOLOPARAQUEAPAREZCACON_H


class soloParaQueAparezcaCon {

};


#endif //PRUEBAPROYECTOMCAV_SOLOPARAQUEAPAREZCACON_H
