//
// Created by mauri on 30/10/2023.
//

#ifndef PRUEBAPROYECTOMCAV_SOLOPARAQUEAPAREZCAVIEW_H
#define PRUEBAPROYECTOMCAV_SOLOPARAQUEAPAREZCAVIEW_H


class soloparaqueaparezcaview {

};


#endif //PRUEBAPROYECTOMCAV_SOLOPARAQUEAPAREZCAVIEW_H
